algoritmo "semnome"
// Função :
// Autor :
// Data : 06/09/2023
// Seção de Declarações 
var
   boas_vindas:caractere
   marca:caractere
   cor:caractere
   tem_4_portas: logico
inicio
      boas_vindas <- "Olá Mundo"
      marca<- "Fiat"
      cor<- "verde"
      tem_4_portas<- verdadeiro
      escreval(boas_vindas)
      escreval(marca)
      escreval(cor)
      escreval(tem_4_portas)
fimalgoritmo
