algoritmo "semnome"
// Função :
// Autor :
// Data : 06/09/2023
// Seção de Declarações
var
  nome: caractere
  idade: inteiro
  cidade: caractere
inicio

      escreval("Qual é o seu nome: ")
      leia(nome)
      leia(idade)
      escreval("Bem vindo" ,nome, "!")
      escreval("Qual a sua idade: ")


      escreval("tenho", idade, "!")
      
      escreval("onde voce mora: ")
      leia(cidade)
      escreval("moro em" ,cidade, "!")
fimalgoritmo

