algoritmo "semnome"
// Função :
// Autor :
// Data : 05/10/2023
// Seção de Declarações 
var
variavel:inteiro
inicio
leia(variavel)



escolha(variavel)
   caso 1 // O 1 é o valor que queremos verificar
     escreva("voce digitou 1")
   caso 2 // O valor testado agora é o 2
     escreva("voce digitou 2")
      // Mais casos: CASO 3, CASO 4 …

      
   outrocaso
            escreva("voce nao digitou um numero valido")
fimescolha // Finaliza a estrutura ESCOLHA
fimalgoritmo
