algoritmo "semnome"
// Função :
// Autor :
// Data : 13/09/2023
// Seção de Declarações 
var
salario:          real
hora:             inteiro
salario_por_hora: real

inicio
escreva("Digite seu salario:")
leia(salario)
escreval("Seu salario é de ", salario )

leia(hora)
escreval("Seu horario é de ", hora, " H/dia")

salario_por_hora <- (salario/30)/hora
escreval("Seu salário/hora é de ", salario_por_hora )

fimalgoritmo
