algoritmo "semnome"
// Função :
// Autor :
// Data : 20/09/2023
// Seção de Declarações 
var
   celsius:real
   kelvin:real
   soma_kelvin:real
   fahrenheit:real
   fahrenheit2:real
   equacao_fahrenheit:real
inicio
      celsius<-35
      kelvin<-273
      fahrenheit<-1.8
      fahrenheit2<-32
      soma_kelvin<-celsius+kelvin
      escreval("o resultado de soma_kelvin é:")
      equacao_fahrenheit<-celsius*fahrenheit+32
      escreva("o resultado de equacao_fahrenheit é:")
fimalgoritmo
