algoritmo "semnome"
// Função :
// Autor :
// Data : 20/09/2023
// Seção de Declarações 
var
   celsius:inteiro
   kelvin:real
   soma_kelvin:real
   fahrenheit:real
   equacao_fahrenheit:real
inicio
      celsius<-35
      kelvin<-273
      fahrenheit<-1.8+32
      soma_kelvin<-celsius+kelvin
      escreval("o resultado de soma_kelvin é:")
      equacao_fahrenheit<-celsius*fahrenheit
      escreva("o resultado de equacao_fahrenheit é:")
fimalgoritmo
